server:
  port: 50401

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/devhub_realm
      client:
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: 8c92000a-d6ae-4d3e-b5c2-d2a71bb9b172
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/devhub_realm
            user-name-attribute: preferred_username

keycloak:
  realm: devhub_realm
  client-id: spring-boot-client
  client-secret: 8c92000a-d6ae-4d3e-b5c2-d2a71bb9b172
  token-uri: http://localhost:8080/realms/devhub_realm/protocol/openid-connect/token
  userinfo-uri: http://localhost:8080/realms/devhub_realm/protocol/openid-connect/userinfo
  admin-user-create-uri: http://localhost:8080/admin/realms/devhub_realm/users
  roles-uri: http://localhost:8080/admin/realms/devhub_realm/roles
  roles-mapping-uri: http://localhost:8080/admin/realms/devhub_realm/users/%s/role-mappings/realm
  admin-login: admin
  admin-password: adminuser

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG


