server:
  port: 8081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:50401
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=3
            - id: user-service
              uri: http://localhost:50402
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=3

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/devhub-realm

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: user-service
        url: /api/v1/users/v3/api-docs

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
